// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhn6gfI5bI5HqD3tOUvtqRsPvhnioRfTY',
    appId: '1:123645510592:web:5bd530f18bc6e731b23e25',
    messagingSenderId: '123645510592',
    projectId: 'socials-6dbe7',
    authDomain: 'socials-6dbe7.firebaseapp.com',
    storageBucket: 'socials-6dbe7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1OZHvdO9pnBpKvdm5hn41jp2xYMcBqXw',
    appId: '1:123645510592:android:3bfd85b96aedce49b23e25',
    messagingSenderId: '123645510592',
    projectId: 'socials-6dbe7',
    storageBucket: 'socials-6dbe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh6GihQv61sqgtMXo_ZWztLOEd9Wx08Gg',
    appId: '1:123645510592:ios:f335298e9593ba15b23e25',
    messagingSenderId: '123645510592',
    projectId: 'socials-6dbe7',
    storageBucket: 'socials-6dbe7.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh6GihQv61sqgtMXo_ZWztLOEd9Wx08Gg',
    appId: '1:123645510592:ios:f335298e9593ba15b23e25',
    messagingSenderId: '123645510592',
    projectId: 'socials-6dbe7',
    storageBucket: 'socials-6dbe7.appspot.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhn6gfI5bI5HqD3tOUvtqRsPvhnioRfTY',
    appId: '1:123645510592:web:dcb839854c863da6b23e25',
    messagingSenderId: '123645510592',
    projectId: 'socials-6dbe7',
    authDomain: 'socials-6dbe7.firebaseapp.com',
    storageBucket: 'socials-6dbe7.appspot.com',
  );
}
